
CREATE TABLE USERS ( ID NUMBER PRIMARY KEY, USERNAME VARCHAR2(100) UNIQUE NOT NULL, PASSWORD_HASH VARCHAR2(200) NOT NULL, NAME VARCHAR2(150), MOBILE VARCHAR2(20), EMAIL VARCHAR2(150), CREATED_AT DATE DEFAULT SYSDATE );
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PLANS ( CODE VARCHAR2(20) PRIMARY KEY, NAME VARCHAR2(50) NOT NULL, MONTHS NUMBER NOT NULL, RATE NUMBER(10,2) NOT NULL );
CREATE TABLE MEMBERS ( ID NUMBER PRIMARY KEY, NAME VARCHAR2(150) NOT NULL, PLAN VARCHAR2(20) REFERENCES PLANS(CODE), PLAN_RATE NUMBER(10,2), JOIN_DATE DATE, EXPIRY_DATE DATE, WHATSAPP VARCHAR2(20), SECONDARY_CONTACT VARCHAR2(20), EMAIL VARCHAR2(150), ADDRESS VARCHAR2(400), HEIGHT_CM NUMBER(6,2), WEIGHT_KG NUMBER(6,2), BIRTH_DATE DATE );
CREATE SEQUENCE MEMBERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE ATTENDANCE ( ID NUMBER PRIMARY KEY, MEMBER_ID NUMBER REFERENCES MEMBERS(ID), CHECKIN_DATE DATE );
CREATE SEQUENCE ATTENDANCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PAYMENTS ( ID NUMBER PRIMARY KEY, MEMBER_ID NUMBER REFERENCES MEMBERS(ID), AMOUNT NUMBER(10,2), PAID_ON DATE );
CREATE SEQUENCE PAYMENTS_SEQ START WITH 1 INCREMENT BY 1;
INSERT INTO PLANS (CODE, NAME, MONTHS, RATE) VALUES ('SILVER','Silver',1,1000);
INSERT INTO PLANS (CODE, NAME, MONTHS, RATE) VALUES ('GOLD','Gold',3,2700);
INSERT INTO PLANS (CODE, NAME, MONTHS, RATE) VALUES ('PLATINUM','Platinum',6,5000);
INSERT INTO PLANS (CODE, NAME, MONTHS, RATE) VALUES ('DIAMOND','Diamond',12,9000);
COMMIT;
